### ISSUE TITLE
[BUG]  custom模式下页面顶部出现线条

### ISSUE THREAD

**Issue by liu354** [max-team/Mars#138]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33274539/61276143-05026000-a7e2-11e9-93d4-90cf8c188ba3.png)
**Expected behavior**
custom模式下，顶部不出现线条

**Additional context**
class=custom 的高度设为0，但它还有border-bottom。class=swan-app-navigation-bar，也存在border-bottom

**Comment by allen-zh** [comment]
fixed https://github.com/max-team/Mars/commit/88e3e24
