### ISSUE TITLE
[BUG]  页面回退后setNavigationBarTitle 设置的title没有了

### ISSUE THREAD

**Issue by liu354** [max-team/Mars#141]
**Describe the bug**
页面回退后setNavigationBarTitle 设置的title没有了，而是使用navigationBarTitleText里设置的title

**Expected behavior**
页面回退后和setNavigationBarTitle 设置的title保存一致

**Comment by allen-zh** [comment]
由于回退时， 对于 Vue App 之外的全局状态无法完全还原导致

变通方法：在 onShow 时再次 setNavigationBarTitle 设置回退后的页面 title
