### ISSUE TITLE
[BUG]  v-model支持问题

### ISSUE THREAD

**Issue by codeteenager** [max-team/Mars#183]
v-model中绑定的值如果刚开始为空的时候，后面通过input设置值就会不生效，这个在编译成h5是没有问题，但是小程序的都会有这个问题。

 vm.$on("vm.updated", _ => {
          setData(vm, this, true);
 });
这个设置数据不生效

**Comment by allen-zh** [comment]
收到，我们看一下

**Comment by codeteenager** [comment]
您好，请问这个问题解决了吗？

**Comment by allen-zh** [comment]
> 您好，请问这个问题解决了吗？

已解决，正在发版

**Comment by allen-zh** [comment]
> 您好，请问这个问题解决了吗？

已解决，npm 版本
0.2.x: @marsjs/core@0.2.23
0.3.x: @marsjs/core@0.3.6
