### ISSUE TITLE
build(h5): 项目中的 app.vue 文件在编译到 H5 时保留独立 sfc

### ISSUE THREAD

**Issue by allen-zh** [max-team/Mars#36]
为了保留业务中 app.vue 的功能完整，与 H5 框架的 App 壳区分开

**Comment by JingyuanZhang** [comment]
done.
https://github.com/max-team/Mars/commit/a755a2bba8c227b968c379a90d61e28a4422fe4d#diff-c86b91392d11295165949d5f01508199
@allen-zh
