### ISSUE TITLE
dist-h5/public 内容应放在项目根目录

### ISSUE THREAD

**Issue by Toxni** [max-team/Mars#41]
dist-h5 往往应该是在 .gitignore 目录内，导致 dist-h5/public 内的变更无法同步到流水线编译。

**Comment by allen-zh** [comment]
不同平台的编译产物（`dist-*`），会经过特定平台的二次编译（例如小程序开发工具和 vue-cli），编译过程需要特定平台的一些配置，比如小程序的 `project.swan.json` / `project.config.json`，以及 H5 的 `vue.config.js` / `public/index.html`。还有一些例如 postcss 和 browserslist 配置文件，它们作用的范围与所在目录有关，为了针对 H5 配置特定的 browserslist，目前其配置文件也在 `dist-h5` 下。

为了实现这些编译配置以及保持项目编译配置的一致性，将配置和特定文件提交在 `dist-*` 目录下是一个简单的做法，不太好的是不能将 `dist-*` 直接加入 .gitignore 。

如果需要将这个配置都拿到  `dist-*` 外，需要实现统一的针对不同平台不同模块的编译配置以及同步（将编译工具维护的小程序配置同步）。

**Comment by Toxni** [comment]
把配置提出来就有两份配置了，确实不太好维护，可以考虑给 `dist-xx` 改名，并在 `.gitignore` 给配置文件白名单，方便维护&使用。

另外，如果有多个项目，每个都叫 `dist-xx` 也容易混淆，改名也能很好解决问题。

建议：假设项目名称叫 `mars`，`dist-h5` 可改为 `mars-h5`，简单清晰，`.gitignore` 给 `./mars-h5/public` `./mars-h5/vue-config.js` 等配置文件白名单即可。 

@JingyuanZhang

**Comment by meixg** [comment]
不要直接修改 dist-h5 中的任何内容
如果有修改 public 中 html 的需求，可以在 vue.config.js 中对 webpack html plugin 进行配置，使用自定义的模板 @Toxni

**Comment by meixg** [comment]
> 把配置提出来就有两份配置了，确实不太好维护，可以考虑给 `dist-xx` 改名，并在 `.gitignore` 给配置文件白名单，方便维护&使用。
> 
> 另外，如果有多个项目，每个都叫 `dist-xx` 也容易混淆，改名也能很好解决问题。
> 
> 建议：假设项目名称叫 `mars`，`dist-h5` 可改为 `mars-h5`，简单清晰，`.gitignore` 给 `./mars-h5/public` `./mars-h5/vue-config.js` 等配置文件白名单即可。
> 
> @JingyuanZhang

dist 目录的名称，可以在 mars.config.js 中进行配置

**Comment by allen-zh** [comment]
已支持 h5 相关配置  `vue.config.js` / `public/index.html` 都在根目录，可以将 dist-h5 加入 .gitignore
