### ISSUE TITLE
[FEATURE] 支持模板中未用到的组件的 js 在编译时移除

### ISSUE THREAD

**Issue by huanling7731** [max-team/Mars#83]
**问题描述**
供单端使用的组件js，还会在其他端运行时执行，可能引起报错

**预期解决**
单端使用的组件js在其他端不执行，或者提供块级js逻辑适配方式，便于内部处理

**Comment by allen-zh** [comment]
支持模板中未用到的组件的 js 在编译时移除，可以移除未用到的组件的 JS，优化性能。
也可以实现供单端使用的组件 JS 只编译到满足条件的端。

**Comment by allen-zh** [comment]
supported by #86
